# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zdw7287/Downloads/week12/blink_rover_axi/src/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
