-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\pwm\pwm.vhd
-- Created: 2018-02-27 17:41:17
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pwm
-- Source Path: pwm
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pwm IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic
        );
END pwm;


ARCHITECTURE rtl OF pwm IS

  -- Component Declarations
  COMPONENT pwm_mbd
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          period                          :   IN    std_logic_vector(26 DOWNTO 0);  -- ufix27
          duty                            :   IN    std_logic_vector(26 DOWNTO 0);  -- ufix27
          pwm_output                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pwm_mbd
    USE ENTITY work.pwm_mbd(rtl);

  -- Signals
  SIGNAL period_out1                      : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL duty_out1                        : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL pwm_mbd_out1                     : std_logic;

BEGIN
  u_pwm_mbd : pwm_mbd
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              period => std_logic_vector(period_out1),  -- ufix27
              duty => std_logic_vector(duty_out1),  -- ufix27
              pwm_output => pwm_mbd_out1
              );


  period_out1 <= to_unsigned(16#00001F4#, 27);

  duty_out1 <= to_unsigned(16#00000FA#, 27);

END rtl;

