-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\pwm\Subsystem.vhd
-- Created: 2018-02-27 17:39:19
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: pwm/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(26 DOWNTO 0);  -- ufix27
        In2                               :   IN    std_logic_vector(26 DOWNTO 0);  -- ufix27
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_unsigned                     : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL slope1_out1                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL slope1_out1_dtc                  : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL slope_out1                       : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Sum_out1                         : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Switch_out1                      : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL Unit_Delay_out1                  : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL Sum_add_temp                     : unsigned(27 DOWNTO 0);  -- ufix28
  SIGNAL In2_unsigned                     : unsigned(26 DOWNTO 0);  -- ufix27
  SIGNAL Relational_Operator1_relop1      : std_logic;

BEGIN
  In1_unsigned <= unsigned(In1);

  slope1_out1 <= to_unsigned(16#000#, 10);

  slope1_out1_dtc <= resize(slope1_out1, 27);

  enb <= clk_enable;

  slope_out1 <= to_unsigned(16#001#, 10);

  
  Relational_Operator_relop1 <= '1' WHEN Sum_out1 /= In1_unsigned ELSE
      '0';

  
  Switch_out1 <= slope1_out1_dtc WHEN Relational_Operator_relop1 = '0' ELSE
      Sum_out1;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_unsigned(16#0000000#, 27);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Sum_add_temp <= resize(Unit_Delay_out1, 28) + resize(slope_out1, 28);
  
  Sum_out1 <= "111111111111111111111111111" WHEN Sum_add_temp(27) /= '0' ELSE
      Sum_add_temp(26 DOWNTO 0);

  In2_unsigned <= unsigned(In2);

  
  Relational_Operator1_relop1 <= '1' WHEN Sum_out1 <= In2_unsigned ELSE
      '0';

  ce_out <= clk_enable;


  Out1 <= Relational_Operator1_relop1;

END rtl;

