set_property SRC_FILE_INFO {cfile:C:/Users/zdw7287/Downloads/custom/axi_test/src/constraints.xdc rfile:../../../../src/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D20         [get_ports led]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD     LVCMOS33    [get_ports led]
