-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\adder\Subsystem.vhd
-- Created: 2017-02-28 14:04:41
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: adder/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        In2                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Signals
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL In2_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- int16

BEGIN
  In1_signed <= signed(In1);

  In2_signed <= signed(In2);

  -- <S1>/Sum
  Sum_out1 <= In1_signed + In2_signed;

  Out1 <= std_logic_vector(Sum_out1);

END rtl;

